### ISSUE TITLE
Burst not working with Espresso

### ISSUE THREAD

**Issue by RobGThai** [square/burst#48] opened 2015-02-03 21:41 UTC
I setup project using Espresso 2.0 for testing. However, I couldn't get the TestCase's constructor injection to work. I use Gradle wrapper to execute test using ```./gradlew connectedAndroidTest'.

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'

    androidTestCompile 'com.squareup.spoon:spoon-client:1.1.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.0'
    androidTestCompile 'com.android.support.test:testing-support-lib:0.1'
    androidTestCompile 'com.squareup.burst:burst-android:1.0.2'
}
```

```
public class BurstConstructorTest extends TestCase {
    private final EchoCollection echos;

    public BurstConstructorTest() {
        this(null);
    }

    public BurstConstructorTest(EchoCollection echos) {
        this.echos = echos;
    }

    public void testConstructorIsWorking() {
        assertNotNull(echos);
    }
}

```

I also tried changing to:
```
androidTestCompile ('com.squareup.burst:burst-junit4:1.0.2') {
        exclude module : 'hamcrest'
        exclude module : 'hamcrest-core'
        exclude module : 'junit'

    }
    androidTestCompile 'com.squareup.burst:burst-android:1.0.2'
    androidTestCompile 'com.squareup.burst:burst:1.0.2'
```
```
import com.squareup.burst.BurstJUnit4;

import org.junit.Test;
import org.junit.runner.RunWith;

import static junit.framework.Assert.assertNotNull;

@RunWith(BurstJUnit4.class)
public class BurstConstructorTest {
    private final EchoCollection echos;

    public BurstConstructorTest(EchoCollection echos) {
        this.echos = echos;
    }

    @Test
    public void testConstructorIsWorking() {
        assertNotNull(echos);
    }
}
```
This would results in "No Test found."

I modified test case to inject field but the test still fail.
 
```
public class BurstConstructorTest {
    @Burst EchoCollection echos;

    public BurstConstructorTest() {

    }

    @Test
    public void testConstructorIsWorking() {
        assertNotNull(echos);
    }
}
```

Did I miss something important to make it work?

**Comment by dlubarov** [comment] 2015-02-03 22:56
Sorry if this wasn't clear but `burst-android` is only for JUnit 3 tests. For JUnit 4 style Android tests, you should only need `burst-junit4`.

If you haven't already, be sure to use the new instrumentation runner which brings JUnit 4 support, i.e.

    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

If you still get `No Test found.`, I would check logcat; there may be an error there which brings us closer to the root problem.

**Comment by RobGThai** [comment] 2015-02-04 10:09
Yes I use ```AndroidJUnitRunner```.  Still getting failed result after the following update:

Seems that burst-junit4 and Espresso both contain  ```junit``` so excluding is required to run. Could this be the reason?
```Groovy
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'

    androidTestCompile 'com.squareup.spoon:spoon-client:1.1.2'
    androidTestCompile ('com.android.support.test.espresso:espresso-core:2.0')
    androidTestCompile ('com.android.support.test:testing-support-lib:0.1')
    androidTestCompile ('com.squareup.burst:burst-junit4:1.0.2')
    {
        exclude module : 'hamcrest'
        exclude module : 'hamcrest-core'
        exclude module : 'junit'
    }
}
```

Using Field annotated, as it required only one constructor in TestCase (and it must be empty).
```Java
public class BurstConstructorTest {
    @Burst EchoCollection echos;

    public BurstConstructorTest() {

    }

    @Test
    public void testConstructorIsWorking() {
        assertNotNull(echos);
    }
}
```

EchoCollection enum is merely.
```Java
public enum EchoCollection {
    HELLO, WOW, OMG, GREAT
}
```

Stacktrace show: 
> junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertNotNull(Assert.java:218)
at junit.framework.Assert.assertNotNull(Assert.java:211)
at com.robgthai.spoon.hellospoon.burst.BurstConstructorTest.testConstructorIsWorking(BurstConstructorTest.java:19)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:24)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
**at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:270)**
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)


I also notice that JUnit 3 support is dropped together with Android-test. Presumably since Espresso is coming with JUnit4, I should be able to just use JUnit4 example. However, I'm not certain about the annotated ```@RunWith(BurstJUnit4.class)``` part. Without it the test doesn't work. With it I get "No tests found.". I also grabbed Logcat after getting "No tests found." [Gist's Logcat](https://gist.github.com/RobGThai/4329bc095453fb9916eb)

**Comment by dlubarov** [comment] 2015-02-04 10:52
Ah, we ran into this problem as well:

    I/dalvikvm( 3150): Could not find method org.junit.runner.Description.createTestDescription, referenced from method com.squareup.burst.BurstRunner.describeChild
    W/dalvikvm( 3150): VFY: unable to resolve static method 18050: Lorg/junit/runner/Description;.createTestDescription (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/annotation/Annotation;)Lorg/junit/runner/Description;

The issue is that Espresso depends on junit-dep 4.10, while Burst requires 4.11+ as that `createTestDescription` method was added in 4.11.

Since junit and junit-dep include the same classes we have to exclude one of them. I'd suggest excluding junit-dep since it's obsolete, and allowing Burst to bring in junit 4.11.

Here's the config we ended up with:

    dependencies {
      ...
      androidTestCompile "com.squareup.burst:burst-junit4:1.0.2"
      androidTestCompile("com.android.support.test.espresso:espresso-core:2.0") {
        exclude group: 'javax.inject', module: 'javax.inject'
      }
      androidTestCompile "com.android.support.test:testing-support-lib:0.1"
    }

    configurations.all {
      // Espresso depends on the now-obsolete junit-dep module. There's no need for it since we
      // already bring in the main junit module.
      exclude group: 'junit', module: 'junit-dep'

      resolutionStrategy {
        // Espresso depends on version 1.1 of hamcrest, and doesn't work with 1.3. JUnit relies on
        // hamcrest-core 1.3, but seems to work with 1.1. So we need to override gradle's default
        // resolution strategy and force 1.1 to be used.
        force 'org.hamcrest:hamcrest-core:1.1'
        force 'org.hamcrest:hamcrest-integration:1.1'
        force 'org.hamcrest:hamcrest-library:1.1'
      }
    }

**Comment by RobGThai** [comment] 2015-02-04 13:04
Spotted on. One thing I'm not sure is why can't we specifically exclude/force versions on Espresso module itself rather than doing it on all configurations?

Here's my working version.
```Groovy
configurations.all {
    exclude module : 'junit-dep'

    resolutionStrategy {
        force 'org.hamcrest:hamcrest-core:1.1'
        force 'org.hamcrest:hamcrest-integration:1.1'
        force 'org.hamcrest:hamcrest-library:1.1'
    }
}
```

However, this still doesn't work on ```ActivityInstrumentationTestCase2``` tho.

**Comment by dlubarov** [comment] 2015-02-04 19:32
I think excluding junit-dep only from Espresso should work though I haven't tried it.

For forcing hamcrest 1.1, correct me if I'm wrong but as far as I know it can only be done with a global `resolutionStrategy`.

I haven't tried using `ActivityInstrumentationTestCase2` with Espresso 2; what kind of error do you get? We wanted to avoid mixing JUnit 3 and JUnit 4 style so we instead used a rule similar to @JakeWharton's [ActivityRule|https://gist.github.com/JakeWharton/1c2f2cadab2ddd97f9fb].

**Comment by RobGThai** [comment] 2015-02-04 20:28
I didn't use ```@RunWith``` to specified TestRunner so standard ```AndroidJUnitRunner``` should ran that. I believe that is why ```@Burst``` annotation has no effect. 

Here's Logcat.
> I/TestRunner( 4912): started: testEchoBurst(com.robgthai.spoon.hellospoon.echo.EchoActivityTest)
I/MonitoringInstrumentation( 4912): Activities that are still in CREATED to PAUSED: 1
D/dalvikvm( 4912): GC_EXPLICIT freed 7K, 50% free 3689K/7320K, paused 0ms+0ms, total 4ms
D/dalvikvm( 4912): GC_EXPLICIT freed <1K, 50% free 3689K/7320K, paused 0ms+0ms, total 7ms
I/TestRunner( 4912): failed: testEchoBurst(com.robgthai.spoon.hellospoon.echo.EchoActivityTest)
I/TestRunner( 4912): ----- begin exception -----
I/TestRunner( 4912): java.lang.NullPointerException
I/TestRunner( 4912): 	at com.robgthai.spoon.hellospoon.echo.EchoActivityTest.testEchoBurst(EchoActivityTest.java:103)
I/TestRunner( 4912): 	at java.lang.reflect.Method.invokeNative(Native Method)
I/TestRunner( 4912): 	at java.lang.reflect.Method.invoke(Method.java:515)
I/TestRunner( 4912): 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
I/TestRunner( 4912): 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
I/TestRunner( 4912): 	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
I/TestRunner( 4912): 	at junit.framework.TestCase.runBare(TestCase.java:134)
I/TestRunner( 4912): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
I/TestRunner( 4912): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
I/TestRunner( 4912): 	at android.support.test.internal.runner.junit3.DelegatingTestResult.runProtected(DelegatingTestResult.java:90)
I/TestRunner( 4912): 	at junit.framework.TestResult.run(TestResult.java:118)
I/TestRunner( 4912): 	at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:49)
I/TestRunner( 4912): 	at junit.framework.TestCase.run(TestCase.java:124)
I/TestRunner( 4912): 	at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
I/TestRunner( 4912): 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
I/TestRunner( 4912): 	at junit.framework.TestSuite.run(TestSuite.java:238)
I/TestRunner( 4912): 	at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
I/TestRunner( 4912): 	at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:63)
I/TestRunner( 4912): 	at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
I/TestRunner( 4912): 	at org.junit.runners.Suite.runChild(Suite.java:127)
I/TestRunner( 4912): 	at org.junit.runners.Suite.runChild(Suite.java:26)
I/TestRunner( 4912): 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
I/TestRunner( 4912): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
I/TestRunner( 4912): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
I/TestRunner( 4912): 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
I/TestRunner( 4912): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
I/TestRunner( 4912): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
I/TestRunner( 4912): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
I/TestRunner( 4912): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
I/TestRunner( 4912): 	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:270)
I/TestRunner( 4912): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
I/TestRunner( 4912): ----- end exception -----
I/TestRunner( 4912): finished: testEchoBurst(com.robgthai.spoon.hellospoon.echo.EchoActivityTest)

TBH, this is the first time I heard of ActivityRule. What's the case against ```ActivityInstrumentTestCase2```? The example show that would still need to use ```AndroidJUnitRunner``` anyway. I presume it should get the same result, right? Or Burst is working if we use ActivityRule?

**Comment by JakeWharton** [comment] 2015-02-04 20:31
> What's the case against ActivityInstrumentTestCase2? 

Composition is infinitely better than inheritance. Further evidenced by the hilariously awful class name suffix of "2".

**Comment by RobGThai** [comment] 2015-02-04 20:50
Totally agreed on the "2". Inside the app, I don't really like being forced to inherit something either. I'll try ActivityRule.

Is there a new Android example coming up for Burst? 

Gonna get my head around annotation processing so I can contribute rather than just asking question. Any good place to start?

**Comment by dlubarov** [comment] 2015-02-05 22:55
Any luck using `ActivityRule` rather than `ActivityInstrumentationTestCase2`?

Haven't put together an android sample yet but our own tests look similar to

```
@RunWith(BurstJUnit4.class)
public class SomeTestCase {
  @Rule public final ActivityRule activityRule = ...;

  @Burst SomeEnum variant;

  @Test public void testSomething() {
  }
}
```

Burst doesn't actually do compile time annotation processing; the test runner does the "bursting" at runtime.

**Comment by dlubarov** [comment] 2015-02-06 00:16
I put together a sample app - https://github.com/dlubarov/burst-android-example

**Comment by RobGThai** [comment] 2015-02-07 23:05
@dlubarov Thanks, I just got back to this today. I did get ActivityRule and Burst to work together but I couldn't get Spoon to capture the screens for the test. That question is probably belong in Spoon, but if you know the answer, that would help a lot :)

```Java
@RunWith(BurstJUnit4.class)
public class ActivityRuleTest {
    @Rule public ActivityRule<LandingActivity> landingActivity = new ActivityRule<>(LandingActivity.class);

    @Burst
    EchoCollection echos;

    @Test
    public void testLandingActivityExists() {
        assertNotNull("LandingActivity is null", landingActivity); // Passed
    }

    @Test
    public void test_BurstWithActivity() {
        onView(withText(echos.name())).check(matches(isDisplayed()));
    }

    @Test
    public void test_txtHelloVisibleWithEspresso() {
        Spoon.screenshot(landingActivity.get(), "Hello_World_espresso");
        onView(withId(R.id.txtHello)).check(matches(isDisplayed()));
    }
}
```

**Comment by dlubarov** [comment] 2015-02-08 00:43
Currently the spoon code looks for `InstrumentationTestCase` in the stack trace, so it won't work with pure JUnit4 tests.

Maybe try [`UiAutomation.takeScreenshot()`](http://developer.android.com/reference/android/app/UiAutomation.html#takeScreenshot()) instead? Or you could replicate what Spoon does internally: create a bitmap, wrap it in a canvas, get the decor view, and call `View.drawCanvas(Canvas)`.

**Comment by RobGThai** [comment] 2015-02-08 10:40
Thanks, I'm holding off on UiAutomator since I still need to support Gingerbread. I'll take a look inside Spoon and see what I can learn from it.

**Comment by dlubarov** [comment] 2015-02-10 19:37
Closing for now; feel free to re-open if you run into more problems.

**Closed by dlubarov** 2015-02-10 19:37 UTC
